### ISSUE TITLE
[Primitive] Hover card

### ISSUE THREAD

**Issue by pimenovoleg** [radix-ng/primitives#166]
https://www.radix-ui.com/primitives/docs/components/hover-card

**Comment by pawel-twardziak** [comment]
@pimenovoleg I might take this one next as this is quite the same as the `popover` is. What do you think?
I assume just copy-paste and changing click trigger into hover one. Anything else?

**Comment by pimenovoleg** [comment]
> @pimenovoleg I might take this one next as this is quite the same as the `popover` is. What do you think? I assume just copy-paste and changing click trigger into hover one. Anything else?

I'm okay with copying the code for now. We can figure out later what parts make sense to extract into core for better reusability. Go ahead!

**Comment by pawel-twardziak** [comment]
> > @pimenovoleg I might take this one next as this is quite the same as the `popover` is. What do you think? I assume just copy-paste and changing click trigger into hover one. Anything else?
> 
> I'm okay with copying the code for now. We can figure out later what parts make sense to extract into core for better reusability. Go ahead!

Yep, later on, I am aiming to make some parts of `hover card`, `popover` and `tooltip` taken outside and shared. They slightly differ from each other, in geneal the cores are the same. Can we add up any other primitive to the three @pimenovoleg?

**Comment by pimenovoleg** [comment]
> > > @pimenovoleg I might take this one next as this is quite the same as the `popover` is. What do you think? I assume just copy-paste and changing click trigger into hover one. Anything else?
> > 
> > 
> > I'm okay with copying the code for now. We can figure out later what parts make sense to extract into core for better reusability. Go ahead!
> 
> Yep, later on, I am aiming to make some parts of `hover card`, `popover` and `tooltip` taken outside and shared. They slightly differ from each other, in geneal the cores are the same. Can we add up any other primitive to the three @pimenovoleg?
> 
> UPDATE: having the core shared, I will make the CDK even service public for experimenting within `hover card`, `popover` and `tooltip` - makes sense? @pimenovoleg

let's give it a try.
All these elements have a lot in common.

**Comment by pawel-twardziak** [comment]
https://github.com/user-attachments/assets/5c07ccb2-6ce1-4d0e-b53a-0de18c56f9ab
