### ISSUE TITLE
[Primitive] Tooltip: onscroll & changing trigger position behaviour (when open state is controlled)

### ISSUE THREAD

**Issue by mrfrac** [radix-ng/primitives#175]
### Overview

The tooltip must be pinned to `tooltipTrigger` when page is scrolling or tooltipTrigger position changed.
This beahviour must by applied only in case when open state is cotrolled.

### Examples in other libraries

https://codesandbox.io/p/devbox/interesting-resonance-d3rrsc?workspaceId=ws_YF21hxMA1PrVmn99UMB9gU

**Comment by pimenovoleg** [comment]
@pawel-twardziak

**Comment by pawel-twardziak** [comment]
@pimenovoleg does it mean you are assigning a task to me? :)

**Comment by pimenovoleg** [comment]
> @pimenovoleg does it mean you are assigning a task to me? :)

yep :)  I haven’t added you to the team yet, so you’ll need to leave comments on the issues for now so I can assign them to you.

**Comment by pimenovoleg** [comment]
And see what works best for you — whether to do it in a single PR or separate ones. It would be great to close all the tooltip features 🥇

**Comment by pawel-twardziak** [comment]
Well, let's go with it! 😆 🚀

**Comment by pawel-twardziak** [comment]
@pimenovoleg @mrfrac I need those #232 and #234 merged to start this task

**Comment by pawel-twardziak** [comment]
@mrfrac (DW @pimenovoleg) is this ok for you if I refactor `tooltip` and harness `directive composition` of Angular? The same way I did it for `popover`.

**Comment by pimenovoleg** [comment]
> @mrfrac (DW @pimenovoleg) is this ok for you if I refactor `tooltip` and harness `directive composition` of Angular? The same way I did it for `popover`.
> 
> UPDATE: so that we can extract a lot of shared functionalities of `tooltip`, `popover` and `hover card` to kinda common lib :)

Absolutely, this makes sense. Refactoring `Tooltip` and harness directive composition similar to `Popover` sounds like a solid approach.

**Comment by pawel-twardziak** [comment]
> > @mrfrac (DW @pimenovoleg) is this ok for you if I refactor `tooltip` and harness `directive composition` of Angular? The same way I did it for `popover`.
> > UPDATE: so that we can extract a lot of shared functionalities of `tooltip`, `popover` and `hover card` to kinda common lib :)
> 
> Absolutely, this makes sense. Refactoring `Tooltip` and harness directive composition similar to `Popover` sounds like a solid approach.

Awesome 🔥 I am asking cause I always respect what the author thinks about my potential changes to their code, whetheror not  it is ok by them 🫡

**Comment by pimenovoleg** [comment]
> > > @mrfrac (DW @pimenovoleg) is this ok for you if I refactor `tooltip` and harness `directive composition` of Angular? The same way I did it for `popover`.
> > > UPDATE: so that we can extract a lot of shared functionalities of `tooltip`, `popover` and `hover card` to kinda common lib :)
> > 
> > 
> > Absolutely, this makes sense. Refactoring `Tooltip` and harness directive composition similar to `Popover` sounds like a solid approach.
> 
> Awesome 🔥 I am asking cause I always respect what the author thinks about my potential changes to their code, whether or not it is ok by them 🫡

That’s a great mindset, and I really appreciate the respect for ownership! 🙌

**Comment by mrfrac** [comment]
> @mrfrac (DW @pimenovoleg) is this ok for you if I refactor `tooltip` and harness `directive composition` of Angular? The same way I did it for `popover`.
> 
> UPDATE: so that we can extract a lot of shared functionalities of `tooltip`, `popover` and `hover card` to kinda common lib :)

Yes, of course, no problem! thanks :)
