### ISSUE TITLE
[Tooltip] multiple Tooltips not working

### ISSUE THREAD

**Issue by pimenovoleg** [radix-ng/primitives#188]
When using multiple Tooltips not working `[sideOffset]` and others inputs on `rdxTooltipContent`

Example:
https://sb-primitives.radix-ng.com/?path=/story/primitives-tooltip--multiple

**Comment by pimenovoleg** [comment]
@pawel-twardziak

**Comment by pawel-twardziak** [comment]
@pimenovoleg ok, you can assing it ti me, I am on it

**Comment by pawel-twardziak** [comment]
@pimenovoleg status: in progress 🕐
