### ISSUE TITLE
Is it really necessry to use transformers for inputs?

### ISSUE THREAD

**Issue by pawel-twardziak** [radix-ng/primitives#193]
Hi guys, @pimenovoleg @olegdenisov @zizifn @lskramarov @mrfrac 

my question is quite simple :)

Do we really need this:

```TS
input<number, NumberInput>(0, { transform: numberAttribute });
```

From Angular perspective, this brings no value imho. So, why do we need it?

In addition, that changes got merged and broke some functionality (my comments did not get responded) -> https://github.com/radix-ng/primitives/pull/189

Concluding, what is the code of conduct for the contribution if things get merged without responding comments? I am a bit confused bacause I am giving my time and experience and there is no reaction to my comments.

Regards :)

**Comment by pimenovoleg** [comment]
@pawel-twardziak 
"my comments did not get responded" sry, I dont see any comments %( lets fix it

Why use transform:
- Consistency: Ensures input values are always in the correct type.
- Validation: Helps in easily validating inputs. For example, you can prevent users from entering non-numeric characters if the input is transformed correctly.
- Simplifies Logic: When input values are converted to the correct type upfront, it reduces the need for extra type-checking in your application logic.

**Comment by pimenovoleg** [comment]
rolled back these changes

**Comment by pawel-twardziak** [comment]
Thanks for the answer @pimenovoleg 

Regarding the explanations:

- consistency: they are always in correct yup because Angular inputes are typed
- validation: user cannot pass any value of incorrect type because Angular build will fail (Angular typescrip language service is the guard)
- simplifies logic: it is the other way around because the transformers double the native functionality of Angular

And my comments there (I dunno why you cannot see them 😢 ):

![obraz](https://github.com/user-attachments/assets/030e5c20-af13-482b-83dd-f6dbbe76ce60)
![obraz](https://github.com/user-attachments/assets/f017e4c8-6abd-4b21-b9f8-6b7ac9372b22)
![obraz](https://github.com/user-attachments/assets/83dc0da2-5af1-4563-8a53-528258860221)

I don't want to sound harsh :) I just love Angular :)

**Comment by pimenovoleg** [comment]
<img width="1041" alt="image" src="https://github.com/user-attachments/assets/80e76489-bd86-493f-9fd3-e5366b19b3e7" />


I dont see any comments %( mb u dont apply comments to review? Its need to be visible for all

**Comment by pawel-twardziak** [comment]
hmmmm aaa damn! I did not apply.. you are right :) Thanks! @pimenovoleg

**Comment by pawel-twardziak** [comment]
Now applied 🚀

**Comment by pawel-twardziak** [comment]
Sorry, my bad, guys.

**Comment by pimenovoleg** [comment]
its ok. It's better to speak up than stay silent.

In the next few days, I'll look into GitHub and add you to the contributors' team. This should help reduce such issues. :)

**Comment by pawel-twardziak** [comment]
On my daily basis I work with Azure Devop and there is no need to apply comments, they are applied automatically :)

**Comment by pimenovoleg** [comment]
`transform: booleanAttribute`
The transformer function will appropriately interpret the presence of the attribute as true.

<radio disabled />

**Comment by pawel-twardziak** [comment]
@pimenovoleg true. But for numbers (the offsets and dimensions in our case) it will not work as expected, right?
And in Angular it is impossible to put `<radio sideOffset />` if the `sideOffset` is an input of a compinent. Angular does not allow it.
![obraz](https://github.com/user-attachments/assets/2d03d8bd-f354-4f79-87d7-adcbfd7fd6c1)

**Comment by pawel-twardziak** [comment]
![obraz](https://github.com/user-attachments/assets/f28814cd-3112-4d5f-8e46-aef4a26dbb34)

**Comment by pawel-twardziak** [comment]
@pimenovoleg You've drawn the inspiration from that?
![obraz](https://github.com/user-attachments/assets/eef00b9b-3752-408d-a039-356d9322515e)

**Comment by pawel-twardziak** [comment]
Ok, I see it. When I change this 
![obraz](https://github.com/user-attachments/assets/89cb901e-88a4-4810-9464-7d79b03c2ede)

The error is never thrown again:
![obraz](https://github.com/user-attachments/assets/476deb4c-6d12-4d43-a5f2-67bcf05ff145)

Now I get your point @pimenovoleg . However, in is not a common practise to use those transformers. I've never seen that pattern along my 7 years experience with Angular :)

The default way inputs are defined in Angular make them easy to recognize they are Angular inputs at glance becasue we always need to pass any value like this `sideOffset=""` so that Angular devs will get surprised and confused a bit when they see `sideOffset ` without any value assigned.

Concluding, I recommend to rethink the need of using those transformers :)
IMHO, they are unnecessary as regular transformers in Angular ecosystem.

**Comment by pimenovoleg** [comment]
Some times we need describe `html` like:

```
<!-- does not compile without the numberAttribute transform -->
<element radius="100"/>

<!-- works with or without the numberAttribute transform -->
<element [radius]="100"/>
```
The same for **booleanAttribute**.

If u check angular/core or angular/material (components) – it's very useful practices

**Comment by pawel-twardziak** [comment]
Ok, you are right. New thing for me and for many other Angular devs I guess. Great investigation from you @pimenovoleg 👏 
Let's apply it then 🚀
