### ISSUE TITLE
[Popover] Add PopoverAnchor directive

### ISSUE THREAD

**Issue by pimenovoleg** [radix-ng/primitives#199]
### Overview

https://www.radix-ui.com/primitives/docs/components/popover#anchor

### Examples in other libraries

https://originui.com/dropdowns-popovers (last example)

How use it:
https://github.com/origin-space/originui/blob/main/components/popovers/popover-09.tsx

**Comment by pimenovoleg** [comment]
It might be worth refining the method `getPositionStrategy` to provide a _link_ to the `anchored element` instead of the `trigger element` when an anchor is present.

**Comment by pawel-twardziak** [comment]
@pimenovoleg yes, true, will do :)

**Comment by pawel-twardziak** [comment]
@pimenovoleg I will make it on top of the animation branch - to avoid conflict, so that once the animation branche get merged, this will be also ready to merge without conflicts.

**Comment by pawel-twardziak** [comment]
@pimenovoleg I am on it right now. Almost done. First question: 

the anchor must be within the root like this:
```html
<ng-container rdxPopoverRoot>
  <div rdxPopoverAnchor>Anchor</div>
</ng-container>
```

or the anchor can also come from outside like this:
```html
<div #anchor="rdxPopoverAnchor">Anchor</div>
<ng-container rdxPopoverRoot [anchor]="anchor"></ng-container>
```

As for me, I am pretty sure both should be possible for developers.

**Comment by pimenovoleg** [comment]
> @pimenovoleg I am on it right now. Almost done. First question:
> 
> the anchor must be within the root like this:
> 
> ```
> <ng-container rdxPopoverRoot>
>   <div rdxPopoverAnchor>Anchor</div>
> </ng-container>
> ```
> 
> or the anchor can also come from outside like this:
> 
> ```
> <div #anchor="rdxPopoverAnchor">Anchor</div>
> <ng-container rdxPopoverRoot [anchor]="anchor"></ng-container>
> ```
> 
> As for me, I am pretty sure both should be possible for developers.

prefer 1 solution.

https://github.com/origin-space/originui/blob/main/components/popovers/popover-09.tsx#L77
As you can see, when using Radix, the anchor is defined as a separate nested "component." In this example, it is used within the Card.

**Comment by pawel-twardziak** [comment]
@pimenovoleg yes, I've seen it to check what is the implementation there. The first is ok. But what when a dev wants to use an anchor that cames from e.g. its parent component because the designers wants the content to be positioned against an anchor that is somewhere else on the page? E.g. I click a button in the footer and something pops up near the header.

I reckon this is a real scenario and popover should be able to consume an external variable as the anchor.

**Comment by pawel-twardziak** [comment]
Even though it is not there yet in the React implementation :)

**Comment by pawel-twardziak** [comment]
I believe the advantage of this library could be a great functional flexibility being headless at the same time :)

**Comment by pimenovoleg** [comment]
I agree, designers' imagination knows no bounds! :)

If both options can be implemented – that would be great.

**Comment by pawel-twardziak** [comment]
They are already implemented :) So I would have to revert some piece of the code :D Great, I am keeping it :)

**Comment by pawel-twardziak** [comment]
@pimenovoleg I cannot push directly to the repo, I still need to work on the fork.
![obraz](https://github.com/user-attachments/assets/18827343-b1db-4d61-aade-66b8914f15ed)

**Comment by pimenovoleg** [comment]
> @pimenovoleg I cannot push directly to the repo, I still need to work on the fork. ![obraz](https://private-user-images.githubusercontent.com/180847852/396221532-18827343-b1db-4d61-aade-66b8914f15ed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQzNzM0NjEsIm5iZiI6MTczNDM3MzE2MSwicGF0aCI6Ii8xODA4NDc4NTIvMzk2MjIxNTMyLTE4ODI3MzQzLWIxZGItNGQ2MS1hYWRlLTY2Yjg5MTRmMTVlZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxNlQxODE5MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNDlhYjJlOGUxYTIzOWQ5Nzc4NTVhYjU4NTNjZTVkZmZmMjkzYTIwYjkwMTllMDVhNDI1ZDM2ZTdlZWFmZTIyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.pVL59_OlPd4RVMWoE1yZ_9Vsxv960jwQ1PWikREVcVg)


Interesting, we’ll figure it out. 
<img width="958" alt="image" src="https://github.com/user-attachments/assets/bddd53bf-9049-4402-b6f7-68c34dac90d5" />

**Comment by pimenovoleg** [comment]
@pawel-twardziak 

Sorry for the obvious steps ahead :) Please try cloning the repository again and ensure you're pushing with your own user account.

We tested it with a different user account, and everything worked fine.

**Comment by pawel-twardziak** [comment]
> @pawel-twardziak
> 
> Sorry for the obvious steps ahead :) Please try cloning the repository again and ensure you're pushing with your own user account.
> 
> We tested it with a different user account, and everything worked fine.

@pimenovoleg no problem at all, that is totally fine. Will clone again :)
