### ISSUE TITLE
Primitives / Radio Group: Tab causes value to change / keyboard inputs feel off

### ISSUE THREAD

**Issue by ValentinFunk** [radix-ng/primitives#95]
### Current Behavior

When tabbing through a radio group the tabbed-to radiobox becomes selected. Arrow keys do not change the value.

### Expected behavior

You can tab to give the radiogroup focus, then change the value by using arrow keys

### Reproducible example

Compare examples:
- https://www.radix-ng.com/?path=/docs/primitives-radio-group--docs
- https://www.radix-ui.com/primitives/docs/components/radio-group

**Comment by pimenovoleg** [comment]
@ValentinFunk 

Thank you for reporting this issue! We've added support for the keyManager, which should resolve the problem. 
Let us know if you encounter any further issues.

https://www.radix-ng.com/?path=/docs/primitives-radio-group--docs

**Comment by ValentinFunk** [comment]
Looks great and that was very quick, thank you!
