### ISSUE TITLE
[Primitives] Popover

### ISSUE THREAD

**Issue by pimenovoleg** [radix-ng/primitives#97]
https://www.radix-ui.com/primitives/docs/components/popover

**Comment by pawel-twardziak** [comment]
sure, I like the repo and the concept. Could you @pimenovoleg assign me to the task and change the status to `in progress`? Or can I do that on my own somehow - it seems like I cannot do so on my own?

**Comment by pawel-twardziak** [comment]
ooo you've assigned me to this, thanks. what about the status? Can we align it and make it `in progress`?

**Comment by pawel-twardziak** [comment]
I cannot change it myself @pimenovoleg 
![obraz](https://github.com/user-attachments/assets/0174e732-1c7c-4876-a27e-41975d51aa91)

**Comment by pimenovoleg** [comment]
done 👍

**Comment by pimenovoleg** [comment]
@pawel-twardziak hi

- If you already have some progress, you can create a PR Draft.
- If you need to discuss something, feel free to write in Discord. (https://discord.gg/NaJb2XRWX9)

**Comment by pawel-twardziak** [comment]
Hi @pimenovoleg, thanks I was on a small vacation, today I will kick it off. Will connect on Discord too.

**Comment by pawel-twardziak** [comment]
@pimenovoleg the behaving must be the same as it is for the react implementation there https://www.radix-ui.com/primitives/docs/components/popover ? Clickable, not hoverable?

**Comment by pawel-twardziak** [comment]
@pimenovoleg the behaving must be the same as it is for the react implementation there https://www.radix-ui.com/primitives/docs/components/popover ? Clickable, not hoverable?

**Comment by pimenovoleg** [comment]
> @pimenovoleg the behaving must be the same as it is for the react implementation there https://www.radix-ui.com/primitives/docs/components/popover ? Clickable, not hoverable?

Сlickable, As I see from the code, the trigger only handles clickability.

https://github.com/radix-ui/primitives/blob/main/packages/react/popover/src/Popover.tsx#L150

**Comment by pawel-twardziak** [comment]
@pimenovoleg tomorrow evening I will raise a beta PR for this

**Comment by pawel-twardziak** [comment]
@pimenovoleg any other task I could work on? :) 

![obraz](https://github.com/user-attachments/assets/2eab5f0e-b684-4523-987f-0361b431f487)

**Comment by pimenovoleg** [comment]
> @pimenovoleg any other task I could work on? :)
> 
> ![obraz](https://private-user-images.githubusercontent.com/180847852/394813356-2eab5f0e-b684-4523-987f-0361b431f487.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM5MzYzODksIm5iZiI6MTczMzkzNjA4OSwicGF0aCI6Ii8xODA4NDc4NTIvMzk0ODEzMzU2LTJlYWI1ZjBlLWI2ODQtNDUyMy05ODdmLTAzNjFiNDMxZjQ4Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxMVQxNjU0NDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZTlhODg1YTVhYzYxMGI3NjlhMjk1NWMyODEwNGU0NWQ0ZmFlMmNkY2I2NjU2MGY0Y2FmOTVkMzRjYjgzMTg3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.J_D59N8Y086mWPYUZdhgSJnsqwe8HtPcp3UFTdQ06G8)

It would be great to improve the tooltip.
What’s particularly interesting is validating its ability to move dynamically along with the slider (mousemove).
